<!-- meanmenu JS ============================================ -->
<script src="<?php echo base_url('public/js/jquery.meanmenu.js'); ?>"></script>
<!-- mCustomScrollbar JS ============================================ -->
<script src="<?php echo base_url('public/js/jquery.mCustomScrollbar.concat.min.js'); ?>"></script>
<!-- sticky JS ============================================ -->
<script src="<?php echo base_url('public/js/jquery.sticky.js'); ?>"></script>
<!-- scrollUp JS ============================================ -->
<script src="<?php echo base_url('public/js/jquery.scrollUp.min.js'); ?>"></script>
<!-- counterup JS ============================================ -->
<script src="<?php echo base_url('public/js/counterup/jquery.counterup.min.js'); ?>"></script>
<script src="<?php echo base_url('public/js/counterup/waypoints.min.js'); ?>"></script>
<script src="<?php echo base_url('public/js/counterup/counterup-active.js'); ?>"></script>
<!-- peity JS ============================================ -->
<script src="<?php echo base_url('public/js/peity/jquery.peity.min.js'); ?>"></script>
<script src="<?php echo base_url('public/js/peity/peity-active.js'); ?>"></script>
<!-- sparkline JS ============================================ -->
<script src="<?php echo base_url('public/js/sparkline/jquery.sparkline.min.js'); ?>"></script>
<script src="<?php echo base_url('public/js/sparkline/sparkline-active.js'); ?>"></script>
